// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTrack(arg1:string,arg2:string,arg3:number):Promise<main.Tracker>;

export function DeleteTrack(arg1:number):Promise<void>;

export function GetAllTracks():Promise<Array<main.Tracker>>;

export function Greet(arg1:string):Promise<string>;

export function IsHighestID(arg1:number):Promise<boolean>;
