// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTrack(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTrack'](arg1, arg2, arg3);
}

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function GetAllTracks() {
  return window['go']['main']['App']['GetAllTracks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsHighestID(arg1) {
  return window['go']['main']['App']['IsHighestID'](arg1);
}
